db:
  socket: "/var/run/mysqld/mysqld.sock"
  name: "wpdb"
  user: "wpadm"
  passwd: "P@ssw0rd"
  host: "{{ groups['wordpress'] }}/32"
  bind_address: "bind-adrress {{ groups['wordpress'] ]}"

change_port: "80"
wp:
  port: "{{ change_port }}"
